admins: []
forwards:
- source: https://t.me/joinchat/TJduukH4DBEoTHGl
  dest:
  - https://t.me/joinchat/_rkJccHX3QY3Nzhh
  offset: 9903
  end: 0
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 11.0
plugins:
  filter:
    files:
      whitelist:
      - document
      - video
      - video_note
      - nofile
